apiVersion: v1
kind: Service
metadata:
  labels:
    service: person-location-consumer-svc
  name: person-location-consumer-svc
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    service: person-location-consumer-svc
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: person-location-consumer-svc
  name: person-location-consumer-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      service: person-location-consumer-svc
  template:
    metadata:
      labels:
        service: person-location-consumer-svc
    spec:
      containers:
      - image: miyachi/person-location-consumer-svc:latest
        name: person-location-consumer-svc
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: person-location-event-map
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: person-location-event-map
              key: KAFKA_TOPIC
        - name: PYTHONUNBUFFERED
          value: '0'
      restartPolicy: Always
